services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: sveltekit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
